# Generated by Django 3.1.7 on 2021-05-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_No', models.CharField(max_length=9)),
                ('debit_no', models.IntegerField()),
                ('cvv_no', models.IntegerField()),
                ('total_deposite', models.IntegerField()),
                ('total_loan', models.IntegerField()),
                ('total_balance', models.IntegerField()),
                ('open_time', models.DateField()),
            ],
        ),
    ]
