# Generated by Django 3.1.7 on 2021-05-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20210523_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
