# Generated by Django 3.1.7 on 2021-05-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20210520_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialinfo',
            name='total_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='credentialinfo',
            name='total_deposite',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='credentialinfo',
            name='total_loan',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='login_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
