# Generated by Django 3.1.7 on 2021-05-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_logininfo_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='is_login',
            field=models.IntegerField(default=0),
        ),
    ]
