# Generated by Django 3.1.7 on 2021-05-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_logininfo_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginInfo',
        ),
        migrations.AlterField(
            model_name='credentialinfo',
            name='total_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='credentialinfo',
            name='total_deposite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='credentialinfo',
            name='total_loan',
            field=models.FloatField(default=0.0),
        ),
    ]
