# Generated by Django 3.1.7 on 2021-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('nominee', models.CharField(max_length=255)),
                ('nominee_realt', models.CharField(max_length=255)),
                ('dob', models.DateField(max_length=8)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar', models.IntegerField(max_length=12)),
                ('pan', models.CharField(max_length=10)),
                ('aadhar_img', models.CharField(max_length=2083)),
                ('pan_img', models.CharField(max_length=2083)),
                ('login_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
