# Generated by Django 3.1.7 on 2021-05-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('nominee', models.CharField(max_length=255)),
                ('nominee_realt', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('aadhar', models.IntegerField()),
                ('pan', models.CharField(max_length=10)),
                ('profile_img', models.ImageField(upload_to='profile_img/')),
                ('aadhar_img', models.ImageField(upload_to='aadhar_img/')),
                ('pan_img', models.ImageField(upload_to='pan_img/')),
            ],
        ),
    ]
