# Generated by Django 3.1.7 on 2021-05-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='account',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='profile_img',
            field=models.CharField(default=12, max_length=2083),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='aadhar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
