# Generated by Django 3.1.7 on 2021-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewAccount', '0002_auto_20210517_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='aadhar_img',
            field=models.ImageField(upload_to='aadhar_img'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='pan_img',
            field=models.ImageField(upload_to='pan_img'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='profile_img',
            field=models.ImageField(upload_to='progile_img'),
        ),
    ]
