# Generated by Django 3.1.7 on 2021-05-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewAccount', '0003_auto_20210517_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='mname',
        ),
    ]
