# Generated by Django 3.1.7 on 2021-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewAccount', '0004_auto_20210517_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='account_no',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='cvv',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='debit_no',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
