# Generated by Django 3.1.7 on 2021-05-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewAccount', '0005_auto_20210518_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='debit_no',
        ),
    ]
