# Generated by Django 3.1.7 on 2021-05-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewAccount', '0006_auto_20210518_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='account',
        ),
    ]
