# Generated by Django 3.1.7 on 2021-05-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewAccount', '0007_remove_customerinfo_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='aadhar_img',
            field=models.ImageField(upload_to='aadhar_img/'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='pan_img',
            field=models.ImageField(upload_to='pan_img/'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='profile_img',
            field=models.ImageField(upload_to='profile_img/'),
        ),
    ]
