# Generated by Django 3.1.7 on 2021-05-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('nominee', models.CharField(max_length=255)),
                ('nominee_realt', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('aadhar', models.IntegerField()),
                ('pan', models.CharField(max_length=10)),
                ('profile_img', models.ImageField(upload_to='profile_img/')),
                ('aadhar_img', models.ImageField(upload_to='aadhar_img/')),
                ('pan_img', models.ImageField(upload_to='pan_img/')),
            ],
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(default=0, max_length=100)),
                ('Account_No', models.CharField(max_length=9)),
                ('login_id', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.IntegerField(default=0)),
                ('is_login', models.IntegerField(default=0)),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField()),
            ],
        ),
    ]
