# Generated by Django 3.1.7 on 2021-05-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bazaar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('descrip', models.CharField(max_length=5000)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
