# Generated by Django 3.1.7 on 2021-05-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bazaar', '0002_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=20)),
                ('total_amount', models.FloatField()),
                ('order_id', models.CharField(max_length=200)),
            ],
        ),
    ]
